spring:
  rabbitmq:
    host: ${RABBIT_MQ_SERVER}
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        inventoryQ:
          destination: inventoryQ
        checkInQ:
          destination: checkInQ
server:
  port: 8060

eureka:
  instance:
    preferIpAddress: true
    ip-address: ${MANAGED_IP}
    hostname: booking-service
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER}:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    instance:
      preferIpAddress: true
  healthcheck:
    enabled: true
