spring:
  rabbitmq:
    #host: 192.168.99.100
    host: 18.212.135.186
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        inventoryQ:
          destination: inventoryQ
        checkInQ:
          destination: checkInQ
server:
  port: 8060

eureka:
  client:
    serviceUrl:
      #defaultZone: http://172.17.0.1:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://18.234.107.114:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    instance:
      preferIpAddress: true
  healthcheck:
    enabled: true
