server:
  port: 8065

eureka:
  instance:
    preferIpAddress: true
    hostname: booking-service-api-gateway
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://172.17.0.1:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    instance:
      preferIpAddress: true
  healthcheck:
    enabled: true

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignoredServices: '*'
  routes:
    booking-service:
      path: /api/**
      serviceId: booking-service
      stripPrefix: true
