spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        inventoryQ:
          destination: inventoryQ
server:
  port: 8090

eureka:
  client:
    serviceUrl:
      #defaultZone: http://172.17.0.1:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    instance:
      preferIpAddress: true
  healthcheck:
    enabled: true

originairports:
  shutdown: JFK

