server:
  port: 8002

eureka:
  instance:
    preferIpAddress: true
    ip-address: ${MANAGED_IP}
    hostname: airline-web-client
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER}:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    instance:
      preferIpAddress: true
  healthcheck:
    enabled: true


#security:
  #user:
    #name: guest
    #password: guest123
