server:
  port: 8081

eureka:
  instance:
    preferIpAddress: true
    hostname: fares-service
  client:
    serviceUrl:
      defaultZone: http://172.17.0.1:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    instance:
      preferIpAddress: true
  healthcheck:
    enabled: true
